# train minist with efficientnet-b0
results_dir: '/home/binz/tao-tf2/results_enb0'
encryption_key: nvidia_tlt
data:
  train_dataset_path: '/home/binz/tao-tf2/dataset/flower_17/train'
  val_dataset_path: '/home/binz/tao-tf2/dataset/flower_17/validation'
  # image_mean: [33.328] # mean of MNIST (0.1307 *255)
  preprocess_mode: 'caffe'
train:
  qat: False
  # pretrained_model_path: '/home/binz/Tao/tao-tf2/results_enb0_16bit_train/weights/efficientnet-b0_004_prune.tlt'
  batch_size_per_gpu: 128
  num_epochs: 10
  wandb:
    entity: "metropolis"
    name: "classification_training_wandb_configdump"
    project: "TAO wandb trainings"
    tags:
      - "training"
      - "classification"
model:
  backbone: 'efficientnet-b0'
  input_image_depth: 8

