dataset:
  augmentation:
    rand_hflip: True
    random_crop_min_scale: 0.1
    random_crop_max_scale: 2
    auto_color_distortion: False
    auto_translate_xy: False
  loader:
    prefetch_size: 4
    shuffle_file: False
    shuffle_buffer: 10000
    cycle_length: 32
    block_length: 16
  max_instances_per_image: 100
  skip_crowd_during_training: True
  use_fake_data: False
  num_classes: 91
  train_tfrecords:
    - '/home/scratch.p3/yuw/datasets/coco/train-*'
  val_tfrecords:
    - '/home/scratch.p3/yuw/datasets/coco/val-*'
  val_json_file: '/home/scratch.p3/yuw/datasets/coco/annotations/instances_val2017.json'
  train_dirs: []
  val_dirs: []
train:
  resume_training_checkpoint_path: ""
  init_epoch: 0
  optimizer:
    name: 'sgd'
    momentum: 0.9
  lr_schedule:
    name: 'cosine'
    warmup_epoch: 1
    warmup_init: 0.0001
    learning_rate: 0.2
    annealing_epoch: 10
  amp: True
  checkpoint: "/home/scratch.p3/yuw/tlt3_experiments/imagenet/tf2_effnet_b0/weights/efficientnet-b0_500.tlt"
  num_examples_per_epoch: 100
  moving_average_decay: 0.999
  batch_size: 20
  checkpoint_interval: 5
  validation_interval: ${train.checkpoint_interval}
  l2_weight_decay: 0.00004
  l1_weight_decay: 0.0
  skip_checkpoint_variables: ''
  clip_gradients_norm: 10.0
  image_preview: True
  qat: False
  random_seed: 42
  pruned_model_path: ''
  num_epochs: 20
  label_smoothing: 0.0
  box_loss_weight: 50.0
  iou_loss_type: 'giou'
  iou_loss_weight: 1.0
  results_dir: ''
model:
  name: 'efficientdet-d0'
  input_width: 512
  input_height: 512
  aspect_ratios: '[(1.0, 1.0), (1.4, 0.7), (0.7, 1.4)]'
  anchor_scale: 4
  min_level: 3
  max_level: 7
  num_scales: 3
  freeze_bn: False
  freeze_blocks: []
evaluate:
  batch_size: 8
  num_samples: 5
  max_detections_per_image: 100
  label_map: ''
  max_nms_inputs: 5000
  checkpoint: ''
  trt_engine: ''
  sigma: 0.5
  start_eval_epoch: 1
  results_dir: ''
export:
  batch_size: 8
  dynamic_batch_size: True
  min_score_thresh: 0.3
  checkpoint: ""
  onnx_file: ""
  results_dir: ''
inference:
  checkpoint: ""
  trt_engine: ""
  image_dir: ""
  dump_label: False
  batch_size: 1
  label_map: ''
  min_score_thresh: 0.3
  max_boxes_to_draw: 100
  results_dir: ''
prune:
  checkpoint: ""
  normalizer: 'max'
  equalization_criterion: 'union'
  granularity: 8
  threshold: 0.5
  min_num_filters: 16
  excluded_layers: []
  results_dir: ''
gen_trt_engine:
  results_dir: ''
  onnx_file: ''
  trt_engine: ''
  tensorrt:
    data_type: "fp32"
    max_workspace_size: 2  # in Gb
    min_batch_size: 1
    opt_batch_size: 1
    max_batch_size: 1
    calibration:
      cal_image_dir: ""
      cal_cache_file: ""
      cal_batch_size: 1
      cal_batches: 1
encryption_key: 'nvidia_tlt'
data_format: 'channels_last'
results_dir: '/tmp/'