FROM nvcr.io/nvstaging/tao/tao_tf2_base_image@sha256:1c058ccec0baf90682bc115be40753d10f1421a7427d28d69d48e4e9fc1ddd7d

# Installing the TAO Toolkit source code packages.
WORKDIR /opt/nvidia
COPY dist/*.whl /opt/nvidia/wheels/
RUN python -m pip install pip --upgrade \
    && cd wheels && ls ./*.whl|xargs -I'{}' python -m pip install '{}' \
    && rm *.whl

RUN rm -rf /opt/nvidia/entrypoint.d/*.txt
COPY release/docker/entrypoint.d/* /opt/nvidia/entrypoint.d/

# Changes required from security scan updates.
RUN apt-get update && apt-get install --only-upgrade libksba8 openssl libssl-dev linux-libc-dev -y

# Update pip package
RUN python -m pip install --upgrade joblib jupyter-core mpmath tornado werkzeug setuptools grpcio
# Removing graphviz since pip show shows no dependencies or requirements for it.
# Output of `pip show graphviz`
# Home-page: https://github.com/xflr6/graphviz
# Location: /usr/local/lib/python3.8/dist-packages
# Requires:
# Required-by:
# Updating container python packages
RUN python -m pip uninstall graphviz -y

# Resolving container scan vulnerabilities
ENV NVM_DIR=/usr/local/nvm
RUN source "$NVM_DIR/nvm.sh" \
    && nvm install 20.15.0 --reinstall-packages-from=16.20.2 node \
    && nvm uninstall 16.20.2

ENV NVIDIA_PRODUCT_NAME "TAO Toolkit"
ENV TAO_TOOLKIT_VERSION="4.0.0"
ENV NVIDIA_TAO_TOOLKIT_VERSION="${TAO_TOOLKIT_VERSION}-TF2"
ENV TAO_TELEMETRY_SERVER="https://api.tao.ngc.nvidia.com"

# Microservices entrypoint
ENV FLASK_APP=/usr/local/lib/python3.10/dist-packages/nvidia_tao_tf2/api/app.py

CMD [ "/bin/bash" ]
